### ISSUE TITLE
What licence is this released under?

### ISSUE THREAD

**Issue by AlanApter** [ibrahimsag/canberead#3]
I'd like to try translating this to a foreign language. Would that be allowed?

**Comment by ibrahimsag** [comment]
Yes, please go ahead. I have the basic structure for multiple languages under `src/en` and `src/tr`, but just the first book is translated. Let me know if I can help.

**Comment by AlanApter** [comment]
Thanks! A licence would be good all the same, but I'll go ahead in the meantime.

**Comment by ibrahimsag** [comment]
I have moved on to drawing the figures for principia when this was over, and there wasn't much time to complete that, let alone thinking about a license for this. May I ask as to your preference?

**Comment by AlanApter** [comment]
http://oss-watch.ac.uk/apps/licdiff/ and https://ufal.github.io/public-license-selector/ are questionnaires that supposed to help choose a license.

The MIT License I think is the least restrictive.

**Comment by ibrahimsag** [comment]
I think CC-BY is appropriate, since content is the interesting part. Let me know whether this works for you.

**Comment by AlanApter** [comment]
Of course!
